---
title: "Blessing"
format: text 
editor: visual
---



Loading library and defining functions
```{r}
library(tidyverse)
load_dictionary<- function(file.path) {
  file_content<- readLines(url(file.path), warn= FALSE)
  print(file_content)
  
}

valid_list <- readLines("https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/collins-scrabble-words-2019.txt")
valid_list <- data.frame(word = valid_list, stringsAsFactors = FALSE)

solution_list <- readLines("https://raw.githubusercontent.com/difiore/ada-datasets/main/google-10000-english-usa-no-swears.txt")
solution_list <- data.frame(word = solution_list, stringsAsFactors = FALSE)


```

winnow solution_list to only include words that are also in valid_list

```{r}
solution_list<- intersect(valid_list, solution_list)


```

Now, the words are updated in solution_list



```{r}

pick_solution <- function(x){
  if (is.character(x)) {
    x <- data.frame(word = x, stringsAsFactors = FALSE)
  }
  
  d <- x %>% filter(str_length(word) == 5)
  w <- sample(as.character(d$word), 1)
  w <- str_split_1(w, "")
  return(w)
}


evaluate_guess <- function(guess, solution){
  guess <- toupper(guess)
  guess <- str_split_1(guess,"")
  e <- rep("\U2B1C", 5)
  for (i in 1:5){
    if (guess[i] %in% solution == F){}
    else{ if (guess[i] != solution[i]) {e[i] = "\U1F7E8"}
      else{e[i]= "\U1F7E9"}}
  }
  e <- paste(e, collapse = "")
  return(e)}

solution <- pick_solution(solution_list)
```

Creating the play_wordle function
```{r, include=FALSE}

play_wordle <- function(solution, valid_list, num_guesses = 6) {
  correct <- paste(rep("\U1F7E9", 5), collapse = "")
  lettersleft <- LETTERS
  cat("You have", num_guesses, "chances to guess a 5-letter word.\n")
  cat("You haven't used", paste(lettersleft, collapse = " "), "\n")
  
  guess_df <- data.frame(Guess = character(num_guesses), Result = character(num_guesses), stringsAsFactors = F)
  try <- 1
  
  while (try <= num_guesses) {
    repeat {
      guess <- readline(prompt = paste("Enter guess number", try, ":"))
      guess <- toupper(guess)
      
      if (length(str_split_1(guess, "")) == 5 & guess %in% valid_list$word) {
        break
      } else {
        readline("Invalid guess, please try again <press enter>")
      }
    }
    
    evaluate <- evaluate_guess(guess, solution)
    guess_df[try, "Guess"] <- guess
    guess_df[try, "Result"] <- evaluate
    
    if (identical(evaluate, correct)) {
      print("Congratulations! You guessed correctly!")
      print(guess_df)
      return()
    } else {
      print(evaluate)
      lettersleft <- setdiff(lettersleft, str_split_1(guess, ""))
      print(paste(c("You haven't used", lettersleft), collapse = " "))
      try <- try + 1
    }
  }
  cat("Sorry, you lost. The correct word was:", paste(solution, collapse = ""), "\n")
  print(guess_df)
  return()
}

#Start the game
play_wordle(solution, valid_list, 6)

```

